application:
  version: '0.1'
  developer: 'Laplas'
  technologies:
    - 'Java'
    - 'Spring'
    - 'Servlet'

logging:
  path: ./log

spring:
  datasource:
    data:
      - classpath:/database/embedded.dml.txt
  jpa:
    open-in-view: false

